FROM node:18-alpine
WORKDIR /app

# Enable pnpm
RUN corepack enable

# Copy workspace dependency definitions
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
# Create backend directory and copy its package.json
RUN mkdir -p backend
COPY backend/package.json ./backend/

# Install only backend dependencies
RUN pnpm install --filter backend --prod --frozen-lockfile

# Copy backend source code
# In dev mode, this will be overwritten by the volume mount
COPY ./backend .

EXPOSE 5000
CMD ["pnpm", "run", "dev"]
