// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecxvcxdnrrtiembcjtuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjeHZjeGRucnJ0aWVtYmNqdHVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA4Nzc3MDQsImV4cCI6MjA3NjQ1MzcwNH0.ocANHXFEJkuYsiooVQuJAhVpfB9a8zy5mNUob3X-5Jg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});